from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
import matplotlib.animation as animation
from sklearn.linear_model import LogisticRegression
X,y = make_classification(n_samples=100, n_features=2, n_informative=1,n_redundant=0, n_classes=2, 
                        n_clusters_per_class=1, random_state=42,hypercube=False,class_sep=2) 
plt.figure(figsize = (10,6))
plt.scatter(X[:,0],X[:,1],c=y,cmap='winter', s=100 )
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Perceptron Algorithm")
plt.show()    

def perceptron(X,y):
    
    X = np.insert(X,0,1,axis=1)
    weights = np.ones(X.shape[1])
    lr = 0.1
    
    for i in range(1000):
        j = np.random.randint(0,100)
        y_hat = step(np.dot(X[j],weights)) # y = w0 + w1*x1 + w2*x2
        weights = weights + lr*(y[j]-y_hat)*X[j]
        
    return weights[0],weights[1:]
    
def step(z):
    return 1 if z>=0 else 0 # this is the activation function we use in the perceptron algorithm


intercept_,coef_ = perceptron(X,y)

print(coef_)
print(intercept_)

m = -(coef_[0]/coef_[1]) # slope m = -w1/w2
b = -(intercept_/coef_[1]) # intercept b = -w0/w2

x_input = np.linspace(-3,3,100)
y_input = m*x_input +b


plt.figure(figsize = (10,6))
plt.scatter(X[:,0],X[:,1],c=y,cmap='winter', s=100 )
plt.plot(x_input,y_input,c="red")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Perceptron Algorithm")
plt.show()    

#making animation of the perceptron algorithm 
def perceptron(X,y):
    
    m = []
    b = []
    
    X = np.insert(X,0,1,axis=1)
    weights = np.ones(X.shape[1])
    lr = 0.1
    
    for i in range(200):
        j = np.random.randint(0,100)
        y_hat = step(np.dot(X[j],weights))
        weights = weights + lr*(y[j]-y_hat)*X[j]
        
        m.append(-(weights[1]/weights[2]))
        b.append(-(weights[0]/weights[2]))
        
    return m,b


m,b = perceptron(X,y)

fig, ax = plt.subplots(figsize=(9,5))

x_i = np.arange(-3, 3, 0.1)
y_i = x_i*m[0] +b[0]
ax.scatter(X[:,0],X[:,1],c=y,cmap='winter',s=100)
line, = ax.plot(x_i, x_i*m[0] +b[0] , 'r-', linewidth=2)
plt.ylim(-3,3)

def update(i):

    label = 'epoch {0}'.format(i + 1)
    line.set_ydata(x_i*m[i] + b[i])
    ax.set_xlabel(label)
    

anim = FuncAnimation(fig, update, repeat=True, frames=200, interval=50)
plt.show()

#comparing perceptron with logistic regression algorithm

lor = LogisticRegression()
lor.fit(X,y)

m = -(lor.coef_[0][0]/lor.coef_[0][1])
b = -(lor.intercept_/lor.coef_[0][1])

x_input1 = np.linspace(-3,3,100)
y_input1 = m*x_input + b
plt.figure(figsize=(10,6))
plt.scatter(X[:,0],X[:,1],c=y,cmap='winter',s=100)
plt.plot(x_input,y_input,color='red',linewidth=3) # this plot the line generated by perceptron algorithm
plt.plot(x_input1,y_input1,color='black',linewidth=3) #this plot the line generated by logistic regression 
plt.ylim(-3,2)
plt.show()

#the main diffrence between perceptron and logistic regression is that perceptron stop working after all the data is corrected but logistic regression work till the error is minimized







